language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='xarray dask toolz Cython pykdtree sphinx cartopy rasterio pillow matplotlib
    pyyaml pyproj coveralls configobj coverage codecov'
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
  - CONDA_CHANNEL_PRIORITY='True'
matrix:
  include:
  - env: PYTHON_VERSION=2.7
    os: linux
  - env: PYTHON_VERSION=2.7
    os: osx
    language: generic
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
    language: generic
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
script:
- coverage run --source=pyresample setup.py test && cd docs && mkdir doctest && sphinx-build
  -E -n -b doctest ./source ./doctest && cd ..
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; codecov; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure: efysRf+1NddbJF6lnDYMHRm+qKXROWOTzcP7A+GJ/BGlkpZHQjf5gmE50C+9yHYigRLdVFX/x0aymiNMD1TFiZgA6a05ko+oFqGdEWV1ix/H1c4goTcIwdR0QVxd6MDmZiyyvmfOBWlKBGKv8ojtXbF+y1fxv+ly1AEeVvn1mqY=
    distributions: sdist
    skip_existing: true
    on:
      tags: true
      repo: pytroll/pyresample
notifications:
  slack: pytroll:96mNSYSI1dBjGyzVXkBT6qFt
