language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
before_install:
- sudo add-apt-repository ppa:ubuntugis/ppa -y
- sudo apt-get update -qq
- sudo apt-get install libfreetype6-dev
- sudo apt-get install libgeos-3.3.8 libgeos-c1 libgeos-dev
install:
- pip install git+https://github.com/matplotlib/matplotlib.git
- pip install git+https://github.com/matplotlib/basemap.git
- pip install -e ".[pykdtree]"
- pip install coveralls
script: coverage run --source=pyresample setup.py test
after_success: coveralls
