name: test-environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - configobj
  - Cython
  - dask
  - distributed
  - donfig
  - matplotlib
  - pillow
  - platformdirs
  - pyyaml
  - pyproj
  - pykdtree
  - rasterio
  - shapely
  - scipy
  - sphinx
  - toolz
  - xarray
  - zarr
  - coverage
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - importlib-metadata
  - sphinx-reredirects
